import '@/styles/globals.css'
import {Quicksand} from "next/font/google"
import Head from "next/head"
import NavBar from "../components/NavBar"
import Footer from '@/components/Footer'

const quicksand = Quicksand({
    subsets: ["latin"],
    variable: "--font-quick"

})


export default function App({ Component, pageProps }) {
  return (
   <>
   <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  <main className={`${quicksand.variable} font-quick bg-light w-full min-h-screen`}>
    <NavBar />
    <Component {...pageProps} />
    <Footer />
  </main>
  </>
  )
}
