import '@/styles/globals.css'
import {Quicksand} from "next/font/google"
import Head from "next/head"
import NavBar from "../components/NavBar"
import Footer from '@/components/Footer'
import { AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/router'

const quicksand = Quicksand({
    subsets: ["latin"],
    variable: "--font-quick"

})


export default function App({ Component, pageProps }) {
  
  const router = useRouter();
  return (
   <>
   <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  <main className={`${quicksand.variable} font-quick bg-light w-full min-h-screen`}>
    <NavBar />
    <AnimatePresence mode="wait">
    <Component key={router.asPath} {...pageProps} />

    </AnimatePresence>
    <Footer />
  </main>
  </>
  )
}
