import Head from 'next/head'
import Layout from '../components/Layout'
import AnimatedText from '../components/AnimatedText'
import Image from 'next/image'
import profilePics from "../../public/images/profile/aku.png"
import profilePics2 from "../../public/images/profile/logo.png"
import profilePics3 from "../../public/images/profile/Logo-BEE.png"
import profilePics4 from "../../public/images/profile/hacktiv8.png"
import Link from 'next/link'

export default function Home() {
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/3'>
              <Image src={profilePics} alt="Foto" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Undergraduate Information Technology Student at Telkom University" className='!text-3xl !text-left'/>
              <p className='my-4 text-base font-medium'>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start my-2'>
                <Link href="/dummy.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparant hover:border-dark"
                > Resume </Link>
                <Link href="mailto:argabimantara8@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline'> Contact </Link>
              </div>

              <div className='flex items-center self-center mt-5'>
                <h1 className='font-medium'>Experience Work : </h1>
                <Image src={profilePics2} alt="Foto" className='w-20 h-auto mx-3'/>
                <Image src={profilePics3} alt="Foto" className='w-20 h-auto mx-3'/>
                <Image src={profilePics4} alt="Foto" className='w-20 h-auto mx-3'/>
              </div>

            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
